### ISSUE TITLE
tag, versioning?

### ISSUE THREAD

**Issue by jrmarino** [AdaCore/AdaSAT#1]
This repository has no tags at all.  This makes it hard to establish the versioning scheme (the git hash is not a version).
Could it be tagged now, and again on each release?

**Comment by Fabien-Chouteau** [comment]
Hello @jrmarino,

There's been no release of this project so far, so no tag nor branch. I believe there should be `24.0` and `24.1` release branches by the end of the year.

**Comment by jrmarino** [comment]
The ada language server list specific comments on several repositories for each release.  Ideally every one of those commits would be tagged.   It's been a packaging issue and I've been fudging the versions (treating most as patched 23.0.0) but in the case of adasat, I had to invent the version.

We're trying to help but Adacore's lack of tagging is making things extremely challenging.

**Comment by jrmarino** [comment]
see what I mean?  the ada language server has a release (e.g. 23.0.21) but the dependencies that it requires are not released.  At least they should have a tag that could be treated as a version for packagers.

**Comment by setton** [comment]
Hello @jrmarino - we understand that the lack of versioning is a hassle. Our plan is to transition progressively all these dependencies to use Alire, hopefully this should help a lot.

**Comment by jrmarino** [comment]
why would using alire help in this case?
a) Alire doesn't not help established package repositories to package it
b) Doesn't Alire still need versioning?
c) After bringing up the topic twice, Alire won't even register their inventory on www.repology.com, making it look like a toy.  It would probable take 2 hours tops to generate an index periodically for repology to read, but nobody is putting any importance on it.

**Comment by Fabien-Chouteau** [comment]
> b) Doesn't Alire still need versioning? 

Exactly, which means the release manifests in the Alire index will link version number and commit id.

> c) After bringing up the topic twice, Alire won't even register their inventory on [www.repology.com](http://www.repology.com), making it look like a toy.

Please avoid this kind of comments, as it sounds disrespectful towards to work done by Alire contributors. As far as I can tell, you are the only person who expressed interest in Reprology, which understandably doesn't make it a high priority for the Alire project.

> It would probable take 2 hours tops to generate an index periodically for repology to read, but nobody is putting any importance on it.

Given your knowledge and interest on the matter, you are probably the best candidate to make this happen.

**Comment by jrmarino** [comment]
> Exactly, which means the release manifests in the Alire index will link version number and commit id.

If version numbers are created in the process, great.   But a commit id, while unique, cannot be compared to other commit id to determine which one is greater, so they can't serve as version numbers.

>  As far as I can tell, you are the only person who expressed interest in Reprology, which understandably doesn't make it a high priority for the Alire project.

Repology would be for the Alire project, not for me.  While the benefits to the project should be obvious, for some reason they are not.  This was not meant as an insult, just the truth.  The real projects are listed there.  so what does it mean if it isn't?  And it's not just perception.

> Given your knowledge and interest on the matter, you are probably the best candidate to make this happen.

Fine.  Hand me the credentials to the database and the credentials to the webserver, one that has the authority to start cron jobs.
